#include <vector>
#include <string>

struct Vector2 {
    float x;
    float y;
};
struct Tile {
    float x;
    float y;
    float z;
};
struct Colour {
    float r;
    float g;
    float b;
    float a;
};

struct Block {
    std::string name;
    int blockID;
    float averageDensity;
    float averageLandValue;
};
struct Ethnicity {
    int ethnicity;
    int frequency;
};
struct District {
    std::string name;
    std::string preset;
    int districtID;
    std::vector<Block> blocks;
    float averageLandValue;
    std::vector<Ethnicity> dominantEthnicities;
};
struct RoomNode {
    Vector2 fc;
    Vector2 ltc;
    Tile nc;
    std::vector<void*> w;
    int fh;
    int ft;
    float nwm;
    bool io;
    bool ia;
    bool ib;
    bool ios;
    bool ic;
    bool sll;
    bool sul;
    std::string fr;
    std::string frr;
    bool anf;
    bool wt;
    bool cav;
    bool fav;
};

struct LightZone {
    std::vector<Tile> n;
    Colour areaLightColour;
    float areaLightBright;
};
struct Material {
    int instanceID;
};
struct MaterialKey {
    Material baseMaterial;
    Colour mainColour;
    Colour colour1;
    Colour colour2;
    Colour colour3;
    float grubiness;
};
struct Object {
    int id;
    std::vector<std::string> furnitureClasses;
    int angle;
    Tile anchorNode;
    std::vector<Tile> coversNodes;
    Tile offset;
    std::string furniture;
    std::string art;
    bool useFOVBLock;
    Vector2 fovDirection;
    int fovMaxDistance;
    bool up;
    Tile scale;
    MaterialKey matKey;
    MaterialKey artMatKet;
    std::vector<int> owners;
};
struct ObjectCluster {
    std::string cluster;
    Tile anchorNode;
    int angle;
    float ranking;
    std::vector<Object> objs;
};
struct CullTreeNode {
    int r;
    std::vector<void*> d;
};
struct Room {
    std::string name;
    std::vector<RoomNode> nodes;
    std::vector<void*> openPlanElements;
    std::vector<LightZone> lightZones;
    std::vector<void*> commonRooms;
    int floorID;
    int id;
    int fID;
    int iID;
    std::string preset;
    bool reachableFromEntrance;
    bool isOutsideWindow;
    bool allowCoving;
    std::string floorMaterial;
    MaterialKey floorMatKey;
    std::string ceilingMaterial;
    MaterialKey ceilingMatKey;
    std::string defaultWallMaterial;
    MaterialKey defaultWallKey;
    MaterialKey miscKey;
    std::string colourScheme;
    std::string mainLightPreset;
    bool isBaseNullRoom;
    Tile middle;
    std::vector<ObjectCluster> f;
    std::vector<int> owners;
    std::vector<void*> airVents;
    Password password;
    int cf;
    std::vector<CullTreeNode> cullTree;
    std::vector<void*> above;
    std::vector<void*> below;
    std::vector<void*> adj;
    std::vector<void*> occ;
};
struct StreetTile {
    std::string name;
    Tile worldPos;
    int section;
    int angle;
};
struct Street {
    std::string name;
    int residenceNumber;
    bool isLobby;
    bool isMainLobby;
    bool isOutside;
    int access;
    std::vector<Room> rooms;
    std::string designStyle;
    int streetID;
    int district;
    std::vector<Tile> tiles;
    std::string streetSuffix;
    bool isAlley;
    bool isBackstreet;
    std::vector<void*> sharedGround;
    std::vector<StreetTile> streetTiles;
};
struct Building {
    int buildingID;
    std::string name;
    std::vector<void*> floors;
    std::string preset;
    int facing;
    bool isInaccessible;
    std::vector<void*> sideSigns;
    std::vector<void*> airDucts;
    std::string designStyle;
    Colour wood;
    std::string floorMaterial;
    MaterialKey floorMatKey;
    std::string ceilingMaterial;
    MaterialKey ceilingMatKey;
    std::string defaultWallMaterial;
    MaterialKey defaultWallKey;
    std::string extWallMaterial;
    MaterialKey extWallKey;
    std::string colourScheme;
    std::string floorMatOverride;
    std::string ceilingMatOverride;
    std::string wallMatOverride;
    std::string floorMatOverrideB;
    std::string ceilingMatOverrideB;
    std::string wallMatOverrideB;
};
struct GlobalTile {
    int tileID;
    Vector2 floorCoord;
    Tile globalTileCoord;
    bool isOutside;
    bool isObstacle;
    bool isAlley;
    bool isBackstreet;
    bool isEdge;
    int rotation;
    bool isEntrance;
    bool isMainEntrance;
    bool isStairwell;
    int stairwellRotation;
    bool isElevator;
    int elevatorRotation;
    bool isTop;
    bool isBottom;
    bool useOptimizedFloor;
    bool useOptimizedCeiling;
};
struct CityTile {
    std::string name;
    int blockID;
    int districtID;
    Vector2 cityCoord;
    Building building;
    std::vector<GlobalTile> outsideTiles;
    int density;
    int landValue;
};
struct VisualTraits {
    int group;
    Colour skinColourRange1;
    Colour skinColourRange2;
    int blackHairRatio;
    int brownHairRatio;
    int blondeHairRatio;
    int gingerHairRatio;
    int RedHairRatio;
    int blueHairRatio;
    int greenHairRatio;
    int purpleHairRatio;
    int pinkHairRatio;
    int greyHairRatio;
    int whiteHairRatio;
    int baldHairRatioMale;
    int shortHairRatioMale;
    int longHairRatioMale;
    int baldHairRatioFemale;
    int shortHairRatioFemale;
    int longHairRatioFemale;
    int straightHairRatioMale;
    int curlyHairRatioMale;
    int balingHairRatioMale;
    int messyHairRatioMale;
    int styledHairRatioMale;
    int mohawkHairRatioMale;
    int afroHairRatioMale;
    int straightHairRatioFemale;
    int curlyHairRatioFemale;
    int balingHairRatioFemale;
    int messyHairRatioFemale;
    int styledHairRatioFemale;
    int mohawkHairRatioFemale;
    int afroHairRatioFemale;
    int blueEyesRatio;
    int brownEyesRatio;
    int greenEyesRatio;
    int greyEyesRatio;
    bool overrideFirst;
    int overrideNameFirst;
    bool overrideSur;
    int overrideNameSur;
    std::vector<int> culturalSimilarities;
    std::vector<Material> ethTraits;
};
struct EthnicityTrait {
    int group;
    float ratio;
    VisualTraits stats;
};
struct FacialFeature {
    int feature;
    int id;
};
struct Descriptors {
    float visualDistinctiveness;
    int build;
    int height;
    float heightCM;
    float weightKG;
    int shoeSize;
    int footwear;
    std::vector<EthnicityTrait> ethnicities;
    Colour skinColour;
    int hairColourCategory;
    Colour hairColour;
    int hairType;
    int eyeColour;
    std::vector<FacialFeature> facialFeatures;
};
struct Aquaintance {
    int from;
    int with;
    std::vector<int> connections;
    int secret;
    float compatible;
    float known;
    float like;
    std::vector<void*> dataKeys;
};
struct Trait {
    int traitID;
    std::string trait;
    int reason;
    std::string date;
};
struct Password {
    std::vector<int> digits;
    int type;
    int id;
    bool used;
    std::vector<int> notes;
};
struct Cloth {
    std::string clothes;
    std::vector<void*> tags;
    Colour baseColor;
    Colour color1;
    Colour color2;
    Colour color3;
    bool borrowed;
};
struct Outfit {
    int category;
    std::vector<Cloth> clothes;
};
struct Citizen {
    int humanID;
    int home;
    std::string debugHome;
    float speedModifier;
    int job;
    std::string birthday;
    float societalClass;
    Descriptors descriptors;
    int blood;
    std::string citizenName;
    std::string firstName;
    std::string casualName;
    std::string surName;
    bool homeless;
    float slangUsage;
    float genderScale;
    int gender;
    int bGender;
    float sexuality;
    float homosexuality;
    std::vector<int> attractedTo;
    int partner;
    int paramour;
    std::string anniversary;
    float sleepNeedMultiplier;
    float snoring;
    float snoreDelay;
    float humility;
    float emotionality;
    float extraversion;
    float agreeableness;
    float conscientiousness;
    float creativity;
    std::vector<Aquaintance> acquaintances;
    std::vector<Trait> traits;
    Password password;
    float maxHealth;
    float recoveryRate;
    float combatSkill;
    float combatHeft;
    float maxNerve;
    float breathRecovery;
    std::string handwriting;
    int sightingMemory;
    std::vector<std::string> favItems;
    std::vector<int> favItemRanks;
    std::vector<int> favCat;
    std::vector<int> favAddresses;
    std::vector<Outfit> outfits;
    int favCol;
};
struct ScreenTraits {
    Colour colour;
    float intensity;
    float flickerColourMultiplier;
    float pulseSpeed;
    float intervalTime;
    bool flicker;
    float range;
};
struct Interactable {
    std::string name;
    int id;
    Tile wPos;
    Tile wEuler;
    Tile lPos;
    Tile lEuler;
    Tile spWPos;
    Tile spWEuler;
    Tile spNode;
    bool spR;
    std::string p;
    std::vector<void*> pv;
    int fp;
    int fsoi;
    int dp;
    MaterialKey mk;
    ScreenTraits lcd;
    std::string lp;
    std::string bp;
    std::string sdp;
    std::string dds;
    int pt;
    int w;
    int r;
    int b;
    int inv;
    float val;
    bool ins;
    float lma;
    float cs;
    bool wo;
    int opp;
    std::string bo;
    std::string sd;
    bool sw0;
    bool sw1;
    bool sw2;
    bool sw3;
    bool locked;
    bool phy;
    bool drm;
    int lzs;
    bool ml;
    int pto;
    std::vector<void*> ssp;
    float mtr;
    bool cr;
    bool rem;
    bool rPl;
    bool spCh;
    bool force;
    std::vector<void*> df;
    std::vector<void*> print;
    std::vector<void*> cap;
    std::vector<void*> sCap;
    int nEvKey;
    float lhc;
    bool ft;
    Password passcode;
};
struct SocialGroup {
    std::string preset;
    int id;
    float decimalStartTime;
    std::vector<int> weekDays;
    std::vector<int> members;
    int meetingPlace;
};
struct Route {
    int w;
    std::vector<int> s;
};
struct Pipe {
    int type;
    std::vector<Route> routes;
    std::vector<int> rooms;
};
struct Criminal {
    int id;
    std::string preset;
    std::string name;
    bool teamLeader;
    int boss;
    float paygrade;
    int teamID;
    bool isOwner;
    int collar;
    int work;
    std::vector<void*> tags;
    int shift;
    float startTime;
    float endTime;
    std::vector<void*> workDaysList;
    float salary;
    std::string salaryString;
};
struct PageContent {
    int page;
    std::string evID;
    int meta;
    std::string discEvID;
    int disc;
    std::string seperation;
    std::string str;
    int order;
};
struct Page {
    std::string id;
    int page;
    std::vector<PageContent> mpContent;
};
struct MetaData {
    int varType;
    float value;
    std::string str;
};
struct Meta {
    int id;
    std::string preset;
    int owner;
    int writer;
    int reciever;
    std::string dds;
    std::vector<MetaData> passed;
    Tile n;
    bool cd;
};
struct City {
    std::string build;
    std::string cityName;
    std::string seed;
    Vector2 citySize;
    int population;
    int playersApartment;
    std::vector<District> districts;
    std::vector<Street> streets;
    std::vector<CityTile> cityTiles;
    std::vector<Citizen> citizens;
    std::vector<Interactable> interactables;
    std::vector<SocialGroup> groups;
    std::vector<Pipe> pipes;
    std::vector<Criminal> criminals;
    std::vector<Page> multiPage;
    std::vector<Meta> metas;
};
